# Generated by Django 2.1.3 on 2018-12-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20181202_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumthread',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
