# Generated by Django 2.1.3 on 2018-12-02 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('ook', '__first__'),#Remove?
        ('forum', '0003_auto_20181202_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumthread',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.DeleteModel(
            name='ForumUser',
        ),
    ]
